version: "2"
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pythonapp
  pythonapp:
    container_name: pythonapp
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo-server
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
